ExoKomodo/daybreak

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- CMakeLists.txt
- Dockerfile
- README.md
- examples/hello.day
- src/CMakeLists.txt
- src/include/lex/lex.h
- src/include/lex/prelude.h
- src/include/lex/token.h
- src/main.c
> 6 lex hello world

- .vscode/launch.json
- Jenkinsfile
- compose_scripts/memory_check.sh
- compose_scripts/test.sh
- docker-compose.yaml
> Update with new template repo defaults

- Dockerfile
- compose_scripts/test.sh
- src/include/api/compiler.h
- src/include/generation/compile_c.h
- src/include/parser/ast.h
> Add flags to internal compile command

- .vscode/launch.json
- .vscode/settings.json
- compose_scripts/test.sh
- examples/variables/variables.day
- src/include/generation/generate_c.h
- src/include/lex/lex.h
- src/include/lex/token.h
- src/include/parser/ast.h
- tests/test_foobar.h
- tests/test_hello_world.h
- tests/test_main.c
- tests/test_variables.h
> Add local variable support

- .vscode/launch.json
- compose_scripts/test.sh
- examples/match/match.day
- src/include/generation/generate_c.h
- src/include/lex/token.h
- src/include/parser/ast.h
- tests/test_foobar.h
- tests/test_hello_world.h
- tests/test_main.c
- tests/test_match.h
- tests/test_variables.h
> Add pattern matching syntax

- .vscode/launch.json
- compose_scripts/test.sh
- examples/foobar/foobar.day
- examples/hello/hello.day
- examples/match/match.day
- examples/pointers/pointers.day
- examples/types/types.day
- examples/variables/variables.day
- src/include/generation/generate_c.h
- src/include/lex/lex.h
- src/include/lex/token.h
- src/include/parser/ast.h
- tests/test_hello_world.h
- tests/test_main.c
- tests/test_types.h
- Simplify function declaration syntax
- Add struct and union support
Closes #19
> Add struct and union support

- .vscode/launch.json
- examples/modules/foo.day
- examples/modules/modules.day
- src/include/generation/generate_c.h
- src/include/lex/token.h
- src/include/parser/ast.h
- src/main.c
> Add import support

- src/include/generation/compile_c.h
> Activate tail recursive optimizations

- .vscode/launch.json
- examples/multiple_imports/bar.day
- examples/multiple_imports/foo.day
- examples/multiple_imports/multiple_imports.day
- src/include/api/compiler.h
- src/include/generation/generate_c.h
- src/include/helpers/system.h
- src/include/lex/lex.h
- tests/test_main.c
- tests/test_multiple_imports.h
> Add multiple imports support

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- CODEOWNERS
> 73: Remove cmake

- src/include/generation/generate_c.h
#define truthy(x) (x)
#define falsey(x) (!(x))
#define lt(x, y) ((x) < (y))
#define lte(x, y) ((x) <= (y))
#define gt(x, y) ((x) > (y))
#define gte(x, y) ((x) >= (y))
Closes #81
> 81: Add missing operators

- README.md
> 91: Fix build status. Update GCC instructions.

- Jenkinsfile
- config.env
- docker-compose.yaml
> 108: Move env vars into environment

- README.md
> 137: add bootstrap status badge

- euler/004/problem.day
- euler/008/problem.day
- examples/foobar/foobar.day
- examples/pointers/pointers.day
- src/include/generation/generate_c.h
- src/main.day
> 84: Make parameters immutable

- examples/modules/foo.day
- examples/modules/modules.day
- src/include/generation/generate_c.h
- src/include/lex/token.h
> 132: Add namespacing with slashes

- Dockerfile
> 161: Move to debian slim

- .devcontainer/devcontainer.json
- .devcontainer/tools/docker/install.sh
- .devcontainer/tools/git/gitconfig
- .devcontainer/tools/git/install.sh
- .devcontainer/tools/install.sh
- .devcontainer/tools/vim/install.sh
- .devcontainer/tools/zsh/install.sh
- .devcontainer/tools/zsh/install_zprezto.zsh
- Dockerfile
- README.md
- docker-compose.yaml
> 159: Recommend devcontainer

- .gitattributes
> 171: Enable docker development on windows

- .vscode/launch.json
- Dockerfile
- compose_scripts/test.sh
- examples/enum/enum.day
- src/include/generation/generate_c.h
- src/include/lex/token.h
- src/include/log/log.h
- src/include/parser/ast.h
- tests/include/test_enum.h
- tests/test_main.day
> 196: add enum support

- .github/workflows/bootstrap.yml
- README.md
> DAY-206: Store C sources

- README.md
> Rename repo to daybreak
